#!/usr/bin/env python3
"""Aggregate causal_rectify_eval.py into W2C / PPR / FCR / Δ_critique tables."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_rows(path: Path):
    return [json.loads(l) for l in open(path) if l.strip()]


def mean(xs):
    return sum(xs) / len(xs) if xs else 0.0


def analyze(rows):
    # Collect all keys
    keys = sorted({k for r in rows for k in r["results"]})
    metrics = {}
    for key in keys:
        w2c1 = mean([r["results"][key]["acc@1"] for r in rows])
        ppr1 = mean([r["results"][key]["ppr@1"] for r in rows])
        # FCR: among actionable teacher critiques
        actionable = [r for r in rows if r.get("actionable")]
        fcr = (
            mean([r["results"][key]["acc@1"] for r in actionable])
            if actionable and key in actionable[0]["results"]
            else None
        )
        # Localization-conditioned (only meaningful when t_star present in result)
        hit = [
            r
            for r in rows
            if r["results"][key].get("t_star") is not None
            and r.get("t_star")
            and r["results"][key].get("t_star") == r.get("t_star")
        ]
        # For true feedback cells, t_star in result equals row t_star by construction.
        # Loc-conditioned uses whether teacher localization is non-trivial (>=1).
        loc_ok = [r for r in rows if (r.get("t_star") or 0) >= 1]
        loc_bad = [r for r in rows if (r.get("t_star") or 0) < 1]
        metrics[key] = {
            "W2C@1_pct": round(100 * w2c1, 2),
            "PPR@1_pct": round(100 * ppr1, 2),
            "FCR@1_pct": round(100 * fcr, 2) if fcr is not None else None,
            "n_actionable": len(actionable),
            "W2C_loc_ok_pct": round(100 * mean([r["results"][key]["acc@1"] for r in loc_ok]), 2)
            if loc_ok
            else None,
            "W2C_loc_missing_pct": round(
                100 * mean([r["results"][key]["acc@1"] for r in loc_bad]), 2
            )
            if loc_bad
            else None,
        }

    # Delta critique: true plan vs shuffled plan
    deltas = {}
    for edit in ("full_regen", "prefix_rewrite"):
        true_k = f"localization_analysis_plan__{edit}"
        shuf_k = f"shuffled_plan__{edit}"
        if true_k in metrics and shuf_k in metrics:
            deltas[edit] = round(
                metrics[true_k]["W2C@1_pct"] - metrics[shuf_k]["W2C@1_pct"], 2
            )

    # 2D W2C matrix
    feedbacks = [
        "regenerate",
        "wrong_only",
        "localization",
        "localization_analysis",
        "localization_analysis_plan",
        "freeform",
    ]
    edits = ["full_regen", "prefix_rewrite"]
    matrix = {}
    for fb in feedbacks:
        matrix[fb] = {}
        for ed in edits:
            k = f"{fb}__{ed}"
            matrix[fb][ed] = metrics.get(k, {}).get("W2C@1_pct")

    return {
        "n_rows": len(rows),
        "pct_actionable": round(100 * mean([1.0 if r.get("actionable") else 0.0 for r in rows]), 2),
        "metrics": metrics,
        "delta_critique_W2C": deltas,
        "w2c_matrix": matrix,
    }


def to_tex(summary: dict) -> str:
    matrix = summary["w2c_matrix"]
    lines = [
        "% auto-generated by aggregate_causal_rectify.py",
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"Feedback & Full regenerate W2C@1 & Prefix rewrite W2C@1 \\",
        r"\midrule",
    ]
    labels = {
        "regenerate": "Regenerate",
        "wrong_only": "Wrong only",
        "localization": "Localization",
        "localization_analysis": "Loc.+Analysis",
        "localization_analysis_plan": "Loc.+Analysis+Plan",
        "freeform": "Free-form why/how",
    }

    def fmt(x):
        return "--" if x is None else f"{x:.1f}"

    for fb, lab in labels.items():
        if fb not in matrix:
            continue
        lines.append(
            f"{lab} & {fmt(matrix[fb].get('full_regen'))} & {fmt(matrix[fb].get('prefix_rewrite'))} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]

    # PPR / FCR / delta
    lines += [
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"Cell & PPR@1 & FCR@1 \\",
        r"\midrule",
    ]
    for key, m in sorted(summary["metrics"].items()):
        if key.startswith("shuffled_"):
            continue
        fcr = "--" if m["FCR@1_pct"] is None else f"{m['FCR@1_pct']:.1f}"
        key_tex = key.replace("_", r"\_")
        lines.append(f"{key_tex} & {m['PPR@1_pct']:.1f} & {fcr} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]

    deltas = summary.get("delta_critique_W2C") or {}
    lines += [
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"Edit mode & $\Delta_{\mathrm{critique}}$ (true$-$shuffled) \\",
        r"\midrule",
    ]
    for ed, val in deltas.items():
        ed_tex = ed.replace("_", r"\_")
        lines.append(f"{ed_tex} & {val:.1f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--out_prefix", type=Path, required=True)
    args = ap.parse_args()

    rows = load_rows(args.input)
    summary = analyze(rows)
    args.out_prefix.parent.mkdir(parents=True, exist_ok=True)
    summary_path = args.out_prefix.with_suffix(".summary.json")
    summary_path.write_text(json.dumps(summary, indent=2))
    tex_path = Path(str(args.out_prefix) + "_tables.tex")
    tex_path.write_text(to_tex(summary))
    print(json.dumps(summary, indent=2))
    print(f"Wrote {summary_path}")
    print(f"Wrote {tex_path}")


if __name__ == "__main__":
    main()
