#!/usr/bin/env python3
"""Aggregate PAG controlled_rectify results into table metrics."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_metrics(path: Path) -> dict:
    return json.loads(path.read_text())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results_dir", type=Path, required=True)
    ap.add_argument(
        "--names",
        nargs="+",
        default=["pag_prerl", "pag_ppo400"],
        help="result file prefixes (<name>_at1.metrics.json)",
    )
    ap.add_argument("--base_name", default="pag_prerl", help="Pre-RL row for Delta_base")
    args = ap.parse_args()

    label_map = {
        "pag_prerl": "Pre-RL",
        "pag_ppo400": "PPO",
    }

    rows = {}
    for name in args.names:
        at1 = args.results_dir / f"{name}_at1.metrics.json"
        at8 = args.results_dir / f"{name}_at8.metrics.json"
        if not at1.exists():
            print(f"missing {at1}")
            continue
        m1 = load_metrics(at1)["metrics"]
        m8 = load_metrics(at8)["metrics"] if at8.exists() else {}
        ecr_fix_1 = m1["fix"]["acc@1_pct"]
        regen_1 = m1["regen"]["acc@1_pct"]
        rows[name] = {
            "ECR_gen@1": m1["gen"]["acc@1_pct"],
            "ECR_gen@8": m8.get("gen", {}).get("pass@8_pct"),
            "ECR_fix@1": ecr_fix_1,
            "ECR_fix@8": m8.get("fix", {}).get("pass@8_pct"),
            "Acc_regen@1": regen_1,
            "Delta_rect@1": round(ecr_fix_1 - regen_1, 2),
        }

    if args.base_name in rows:
        base = rows[args.base_name]["ECR_fix@1"]
        for r in rows.values():
            r["Delta_base@1"] = round(r["ECR_fix@1"] - base, 2)

    print(json.dumps(rows, indent=2))
    print()
    print(
        "Method & Checkpoint & ECR_gen@1 & ECR_gen@8 & ECR_fix@1 & ECR_fix@8 "
        "& Acc_regen@1 & d_rect & d_base"
    )

    def fmt(x):
        return "--" if x is None else f"{x:.1f}"

    for name in args.names:
        if name not in rows:
            continue
        r = rows[name]
        label = label_map.get(name, name)
        print(
            f"PAG & {label} & {fmt(r['ECR_gen@1'])} & {fmt(r['ECR_gen@8'])} & "
            f"{fmt(r['ECR_fix@1'])} & {fmt(r['ECR_fix@8'])} & {fmt(r['Acc_regen@1'])} & "
            f"{fmt(r['Delta_rect@1'])} & {fmt(r.get('Delta_base@1'))}"
        )

    tex = args.results_dir / "table_pag_controlled_rectify.tex"
    lines = [
        "% auto-generated by aggregate_table.py",
        r"\begin{tabular}{llccccccc}",
        r"\toprule",
        r"Method & Checkpoint"
        r" & $\mathrm{ECR}_{\mathrm{gen}}^{@1}\uparrow$"
        r" & $\mathrm{ECR}_{\mathrm{gen}}^{@8}\uparrow$"
        r" & $\mathrm{ECR}_{\mathrm{fix}}^{@1}\uparrow$"
        r" & $\mathrm{ECR}_{\mathrm{fix}}^{@8}\uparrow$"
        r" & $\mathrm{Acc}_{\mathrm{regen}}^{@1}\uparrow$"
        r" & $\Delta_{\mathrm{rect}}^{@1}\uparrow$"
        r" & $\Delta_{\mathrm{base}}^{@1}\uparrow$ \\",
        r"\midrule",
    ]
    n_rows = sum(1 for n in args.names if n in rows)
    first = True
    for name in args.names:
        if name not in rows:
            continue
        r = rows[name]
        label = label_map.get(name, name)
        if first:
            method = rf"\multirow{{{n_rows}}}{{*}}{{PAG}}"
            first = False
        else:
            method = ""
        lines.append(
            f"{method} & {label}"
            f" & {fmt(r['ECR_gen@1'])} & {fmt(r['ECR_gen@8'])}"
            f" & {fmt(r['ECR_fix@1'])} & {fmt(r['ECR_fix@8'])}"
            f" & {fmt(r['Acc_regen@1'])} & {fmt(r['Delta_rect@1'])}"
            f" & {fmt(r.get('Delta_base@1'))} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    tex.write_text("\n".join(lines))
    print(f"Wrote {tex}")


if __name__ == "__main__":
    main()
