#!/usr/bin/env python3
"""Aggregate PAG reward-informativeness diagnosis outputs."""
from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path


def variance(xs):
    n = len(xs)
    if n == 0:
        return 0.0
    m = sum(xs) / n
    return sum((x - m) ** 2 for x in xs) / n


def classify_group(bits):
    s = sum(bits)
    if s == 0:
        return "all_zero"
    if s == len(bits):
        return "all_one"
    return "informative"


def load_rows(path: Path):
    return [json.loads(l) for l in open(path) if l.strip()]


def analyze(rows):
    per_row_stats = []
    group_counts = {"all_zero": 0, "all_one": 0, "informative": 0}
    group_draws = 0
    cond_stats = {
        c: {"acc1_sum": 0.0, "passk_sum": 0.0, "n": 0}
        for c in ("specific", "generic", "none", "independent")
    }

    for row in rows:
        res = row["results"]
        M, K = row["M"], row["K"]

        matrix = res["specific"]["matrix"]  # M x K bool
        p_j = [sum(matrix[j]) / K for j in range(M)]
        var_between = variance(p_j)
        var_within = sum(p * (1 - p) for p in p_j) / M
        denom = var_between + var_within
        rho = (var_between / denom) if denom > 1e-12 else None
        per_row_stats.append(
            {
                "idx": row["idx"],
                "p_j": p_j,
                "var_between": var_between,
                "var_within": var_within,
                "rho": rho,
                "degenerate_both": denom <= 1e-12,
            }
        )

        for k in range(K):
            bits = [matrix[j][k] for j in range(M)]
            group_counts[classify_group(bits)] += 1
            group_draws += 1

        acc1 = sum(matrix[j][0] for j in range(M)) / M
        passk = sum((1.0 if any(matrix[j]) else 0.0) for j in range(M)) / M
        cond_stats["specific"]["acc1_sum"] += acc1
        cond_stats["specific"]["passk_sum"] += passk
        cond_stats["specific"]["n"] += 1

        for cond in ("generic", "none", "independent"):
            samples = res[cond]["samples"]
            cond_stats[cond]["acc1_sum"] += float(samples[0])
            cond_stats[cond]["passk_sum"] += float(any(samples))
            cond_stats[cond]["n"] += 1

    rhos = [s["rho"] for s in per_row_stats if s["rho"] is not None]
    mean_between = statistics.fmean(s["var_between"] for s in per_row_stats)
    mean_within = statistics.fmean(s["var_within"] for s in per_row_stats)
    pooled_rho = (
        mean_between / (mean_between + mean_within)
        if (mean_between + mean_within) > 1e-12
        else None
    )

    n_degenerate_both = sum(1 for s in per_row_stats if s["degenerate_both"])
    summary = {
        "n_rows": len(rows),
        "variance_decomposition": {
            "mean_var_between": mean_between,
            "mean_var_within": mean_within,
            "pooled_rho": pooled_rho,
            "mean_rho_per_row": statistics.fmean(rhos) if rhos else None,
            "median_rho_per_row": statistics.median(rhos) if rhos else None,
            "pct_degenerate_both_dims": 100.0 * n_degenerate_both / len(per_row_stats),
        },
        "grpo_group_classification": {
            "n_draws": group_draws,
            "pct_all_zero": 100.0 * group_counts["all_zero"] / group_draws,
            "pct_all_one": 100.0 * group_counts["all_one"] / group_draws,
            "pct_informative": 100.0 * group_counts["informative"] / group_draws,
        },
        "condition_comparison": {},
    }

    for cond, s in cond_stats.items():
        summary["condition_comparison"][cond] = {
            "n": s["n"],
            "CR@1_pct": round(100.0 * s["acc1_sum"] / s["n"], 2),
            "CR@K_pct": round(100.0 * s["passk_sum"] / s["n"], 2),
        }
    return summary, per_row_stats


def fmt_pct(x, nd=1):
    return "--" if x is None else f"{x:.{nd}f}"


def to_tex(summary, ckpt_tag: str):
    vd = summary["variance_decomposition"]
    gc = summary["grpo_group_classification"]
    cc = summary["condition_comparison"]
    lines = [
        "% auto-generated by aggregate_reward_informativeness.py",
        f"% ckpt={ckpt_tag}",
        "",
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"Condition & CR@1 (\%) & CR@K (\%) \\",
        r"\midrule",
        f"Specific critique (avg. over $M$) & {cc['specific']['CR@1_pct']:.1f} & {cc['specific']['CR@K_pct']:.1f} \\\\",
        f"Generic feedback & {cc['generic']['CR@1_pct']:.1f} & {cc['generic']['CR@K_pct']:.1f} \\\\",
        f"No feedback & {cc['none']['CR@1_pct']:.1f} & {cc['none']['CR@K_pct']:.1f} \\\\",
        f"Independent re-solving & {cc['independent']['CR@1_pct']:.1f} & {cc['independent']['CR@K_pct']:.1f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"Variance diagnostic & Value \\",
        r"\midrule",
        f"Mean $\\mathrm{{Var}}_{{\\text{{between}}}}$ & {vd['mean_var_between']:.4f} \\\\",
        f"Mean $\\mathrm{{Var}}_{{\\text{{within}}}}$ & {vd['mean_var_within']:.4f} \\\\",
        f"Pooled $\\rho$ & {fmt_pct(100 * vd['pooled_rho'] if vd['pooled_rho'] is not None else None)}\\% \\\\",
        f"Degenerate examples & {fmt_pct(vd['pct_degenerate_both_dims'])}\\% \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"\begin{tabular}{lc}",
        r"\toprule",
        r"GRPO group type & \% \\",
        r"\midrule",
        f"All-zero & {fmt_pct(gc['pct_all_zero'])}\\% \\\\",
        f"All-one & {fmt_pct(gc['pct_all_one'])}\\% \\\\",
        f"Informative (mixed) & {fmt_pct(gc['pct_informative'])}\\% \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--out_prefix", type=Path, required=True)
    ap.add_argument("--ckpt_tag", default="pag")
    args = ap.parse_args()

    rows = load_rows(args.input)
    summary, per_row_stats = analyze(rows)
    args.out_prefix.parent.mkdir(parents=True, exist_ok=True)

    summary_path = args.out_prefix.with_suffix(".summary.json")
    summary_path.write_text(json.dumps(summary, indent=2))

    per_row_path = args.out_prefix.with_suffix(".per_row.jsonl")
    with open(per_row_path, "w") as f:
        for r in per_row_stats:
            f.write(json.dumps(r) + "\n")

    tex_path = Path(str(args.out_prefix) + "_tables.tex")
    tex_path.write_text(to_tex(summary, args.ckpt_tag))

    print(json.dumps(summary, indent=2))
    print(f"Wrote {summary_path}")
    print(f"Wrote {per_row_path}")
    print(f"Wrote {tex_path}")


if __name__ == "__main__":
    main()
